import Project from '../Project';

const Projects = () => {
    return (
        <section className='section'>
            <h2 className='section__title section__title-gradient projects__line'>My <br /> Projects</h2>
            <div className='projects__container container grid'>
                <Project project={'Redux Store'} technologies={'Javascript, Node, MongoDB, and Heroku.'} description={"This is an online store that allows users to shop online. the original code for this website was refactored to use Redux instead of the context API."} link={'https://ancient-coast-25813.herokuapp.com/'} github={'https://github.com/jameleggleston/Redux-Store'} gif={'https://res.cloudinary.com/dtjtbzifj/image/upload/v1636745529/Screenshot1_xlszjb.jpg'} />
                <Project project={'Workout Tracker'} technologies={'Javascript, Node, MongoDB, and Heroku'} description={"As a gym junkie, I want to be able to view create and track daily workouts. I want to be able to log multiple exercises in a workout on a given day. I should also be able to track the name, type, weight, sets, reps, and duration of exercise. If the exercise is a cardio exercise, I should be able to track my distance traveled."} link={'https://je-workout-tracker.herokuapp.com/?id=6179ecb49b1b8a0016d39360'} github={'https://github.com/jameleggleston/Workout-Tracker'} gif={'https://res.cloudinary.com/dtjtbzifj/image/upload/v1636745645/workout_qniiqy.gif'} />
                <Project project={'Mix N Match'} technologies={"Javascript, Node, MySQL, and Heroku."} description={'This application is a simple dating app that allows users to match with other uses based on mutual beer preference and people with similar desired pronouns. Users are able to sign up and create a profile after being asked questions like name, pronoun, desired pronoun, age, city, hobbies, beer type, and profile picture, among others. Upon signing in with their newly created credentials, users will land at a dashboard where they will view suggested matches based on beer preference and pronouns. The matches cards show profile picture'} link={'http://frozen-inlet-56976.herokuapp.com/login'} github={'https://github.com/jameleggleston/Mix-N-Match'} gif={'https://res.cloudinary.com/dtjtbzifj/image/upload/v1636746107/Login_Signup_zayq0v.png'} />
                <Project project={'Note Taker'} technologies={'avascript, Node, MySQL, and Heroku'} description={"As a small business owner I want to be able to write and save notes, so that I can organize my thoughts and keep track of tasks I need to complete.Once you load the deployed application, you can click the 'Get Started' button to begin. Now you can create a new note, and veiw/delete a previous note. Once you've created your note title and description, you can click the 'save icon' button to add your new note. You must create a note title and description when creating a new note in order for the save icon to appear."} link={'https://vast-tundra-17769.herokuapp.com/'} github={'https://github.com/jameleggleston/Note-Taker'} gif={'https://res.cloudinary.com/dtjtbzifj/image/upload/v1636746285/screenshot1_v0f5jp.jpg'} />
                <Project project={'Sky Gazer'} technologies={"Javascript, HTML, and CSS."} description={"As a user I want to view satellites as they move across the sky in their particular location. The user will input their location and the site will return back information about the location of the satellite and the time of day of the next fly over and will pair with weather data to determine if the user will be able to see the satellite when it flies over in their particular location."} link={'https://jameleggleston.github.io/Sky-Gazer/'} github={'https://github.com/jameleggleston/Sky-Gazer'} gif={'https://res.cloudinary.com/dtjtbzifj/image/upload/v1636746335/Screenshot1_lgeecn.jpg'} />
                <Project project={'Weather Dashboard'} technologies={'Javascript, HTML, and CSS.'} description={"Planning a trip soon and need to know what the weather is going to be? It's import to know the weather for packing. This weather dashboard application allows you to search the current weather and the forcast for the next five days in any city."} link={'https://jameleggleston.github.io/Weather-Dashboard/'} github={'https://github.com/jameleggleston/Weather-Dashboard'} gif={'https://res.cloudinary.com/dtjtbzifj/image/upload/v1636746407/Dashboard_mfxsd2.gif'} />
            </div>
        </section>
    )
}

export default Projects 